import React, { useMemo, useState } from 'react';
import { ChevronDown, ChevronUp, Copy, Eye, EyeOff, GripVertical, Layers3, Plus, Save, Settings2, Trash2, X } from 'lucide-react';
import * as Icons from 'lucide-react';
import { blockCatalog, createBlock } from './blocks';
import { assetPath } from '../../data/media';
import { RichTextEditor } from './RichTextEditor';
import { MediaUploader } from './MediaUploader';
import { MediaGallery } from './MediaGallery';
import { ColorPicker } from './ColorPicker';
import { ContextMenu } from './Chrome';

function CatalogIcon({ name }) { const Icon = Icons[name] || Layers3; return <Icon size={17} />; }

export function BlockBuilder({ value = [], onChange, title = 'Editor de bloques', fullscreen = true }) {
  const [blocks, setBlocks] = useState(value); const [selected, setSelected] = useState(null); const [paletteOpen, setPaletteOpen] = useState(false); const [isFullscreen, setIsFullscreen] = useState(false); const [preview, setPreview] = useState(false);
  const update = (next) => { setBlocks(next); onChange?.(next); };
  const add = (type, index = blocks.length) => { const next = [...blocks]; next.splice(index, 0, createBlock(type)); update(next); setSelected(index); setPaletteOpen(false); };
  const patch = (index, changes) => update(blocks.map((block, blockIndex) => blockIndex === index ? { ...block, ...changes } : block));
  const move = (index, direction) => { const target = index + direction; if (target < 0 || target >= blocks.length) return; const next = [...blocks]; [next[index], next[target]] = [next[target], next[index]]; update(next); setSelected(target); };
  const remove = (index) => { update(blocks.filter((_, blockIndex) => blockIndex !== index)); setSelected(null); };
  const duplicate = (index) => { const copyBlock = JSON.parse(JSON.stringify(blocks[index])); copyBlock.id = `${copyBlock.type}-${Date.now()}`; const next = [...blocks]; next.splice(index + 1, 0, copyBlock); update(next); setSelected(index + 1); };
  const shellClass = `${isFullscreen ? 'block-builder-fullscreen' : ''} ${preview ? 'block-builder-preview' : ''}`;
  return <div className={`block-builder ${shellClass}`}><ContextMenu items={[{ label: 'Añadir bloque', icon: <Plus size={13} />, onClick: () => setPaletteOpen(true) }, { label: 'Vista previa', icon: <Eye size={13} />, onClick: () => setPreview(true) }]} /><div className="block-builder-head"><div><span className="eyebrow orange">Contenido modular</span><h2>{title}</h2><p>{blocks.length} bloque{blocks.length === 1 ? '' : 's'} · arrastra conceptualmente con los controles de orden.</p></div><div className="block-builder-head-actions"><button type="button" onClick={() => setPreview(!preview)}><Eye size={15} /> {preview ? 'Editar' : 'Vista previa'}</button>{fullscreen && <button type="button" onClick={() => setIsFullscreen(!isFullscreen)}>{isFullscreen ? <X size={15} /> : <Settings2 size={15} />} {isFullscreen ? 'Cerrar' : 'Pantalla completa'}</button>}</div></div>{!preview && <div className="block-builder-toolbar"><button type="button" className="button button-primary" onClick={() => setPaletteOpen(!paletteOpen)}><Plus size={16} /> Añadir bloque</button><span><GripVertical size={14} /> Ordena, oculta o duplica cada bloque</span></div>}{paletteOpen && <div className="block-catalog">{blockCatalog.map((item) => <button type="button" key={item.type} onClick={() => add(item.type)}><CatalogIcon name={item.icon} /><span><b>{item.label}</b><small>{item.description}</small></span><Plus size={14} /></button>)}</div>}<div className="block-builder-canvas">{preview ? <div className="block-preview-surface"><BlockPreview blocks={blocks} /></div> : blocks.length ? blocks.map((block, index) => <BlockRow key={block.id} block={block} index={index} count={blocks.length} selected={selected === index} onSelect={() => setSelected(index)} onMove={move} onRemove={remove} onDuplicate={duplicate} onPatch={patch} />) : <button type="button" className="block-builder-empty" onClick={() => setPaletteOpen(true)}><Layers3 size={27} /><b>Empieza con tu primer bloque</b><span>Texto, imagen, galería, formulario o una composición completa.</span></button>}</div></div>;
}

function BlockRow({ block, index, count, selected, onSelect, onMove, onRemove, onDuplicate, onPatch }) {
  const meta = blockCatalog.find((item) => item.type === block.type); return <article className={`block-row ${selected ? 'selected' : ''} ${block.visible === false ? 'hidden-block' : ''}`}><div className="block-row-top" onClick={onSelect}><div className="block-row-title"><GripVertical size={16} /><span className="block-row-icon"><CatalogIcon name={meta?.icon} /></span><span><b>{meta?.label || block.type}</b><small>Bloque {index + 1} · {block.visible === false ? 'Oculto' : 'Visible'}</small></span></div><div className="block-row-actions"><button type="button" onClick={(event) => { event.stopPropagation(); onMove(index, -1); }} disabled={index === 0} title="Subir"><ChevronUp size={15} /></button><button type="button" onClick={(event) => { event.stopPropagation(); onMove(index, 1); }} disabled={index === count - 1} title="Bajar"><ChevronDown size={15} /></button><button type="button" onClick={(event) => { event.stopPropagation(); onPatch(index, { visible: block.visible === false }); }} title="Mostrar u ocultar">{block.visible === false ? <EyeOff size={15} /> : <Eye size={15} />}</button><button type="button" onClick={(event) => { event.stopPropagation(); onDuplicate(index); }} title="Duplicar"><Copy size={15} /></button><button className="danger" type="button" onClick={(event) => { event.stopPropagation(); onRemove(index); }} title="Eliminar"><Trash2 size={15} /></button></div></div>{selected && <div className="block-row-editor"><BlockEditorForm block={block} onChange={(changes) => onPatch(index, changes)} /></div>}</article>;
}

function BlockEditorForm({ block, onChange }) {
  const [galleryItems, setGalleryItems] = useState(block.items || []);
  const textInput = (key, label, type = 'text') => <label className="studio-input-label">{label}<input type={type} value={block[key] ?? ''} onChange={(event) => onChange({ [key]: type === 'number' ? Number(event.target.value) : event.target.value })} /></label>;
  if (block.type === 'text') return <RichTextEditor value={block.content} onChange={(content) => onChange({ content })} label="Texto del bloque" />;
  if (block.type === 'image') return <div className="block-editor-grid"><div><MediaUploader value={block.src ? [{ file: { name: block.src.split('/').pop(), type: 'image/*', size: 0 }, url: block.src }] : []} multiple={false} onChange={(items) => onChange({ src: items[0]?.url || '' })} /><div className="fields two">{textInput('alt', 'Texto alternativo')}{textInput('caption', 'Pie de imagen')}</div></div><div className="block-option-stack"><label>Escala<select value={block.size} onChange={(event) => onChange({ size: event.target.value })}><option value="small">Pequeña</option><option value="medium">Mediana</option><option value="large">Grande</option><option value="full">Ancho completo</option><option value="screen">Pantalla completa</option></select></label><label>Ajuste<select value={block.fit} onChange={(event) => onChange({ fit: event.target.value })}><option value="cover">Cubrir / expandir</option><option value="contain">Ajustar / contener</option><option value="auto">Proporción original</option></select></label></div></div>;
  if (block.type === 'gallery') return <div className="block-editor-grid"><div><MediaUploader value={(block.items || []).map((item) => ({ file: { name: item.src.split('/').pop(), type: 'image/*', size: 0 }, url: item.src }))} onChange={(items) => { const next = items.map((item) => ({ src: item.url, alt: 'Imagen Gigaprint' })); setGalleryItems(next); onChange({ items: next }); }} label="Imágenes de la galería" /><MediaGallery items={galleryItems} layout={block.layout} columns={block.columns} /></div><div className="block-option-stack"><label>Presentación<select value={block.layout} onChange={(event) => onChange({ layout: event.target.value })}><option value="grid">Mosaico</option><option value="masonry">Masonry</option><option value="carousel">Carrusel</option></select></label>{textInput('columns', 'Columnas', 'number')}</div></div>;
  if (block.type === 'media-text') return <div className="block-editor-grid"><div><MediaUploader value={[{ file: { name: block.src?.split('/').pop() || 'imagen', type: 'image/*', size: 0 }, url: block.src }]} multiple={false} onChange={(items) => onChange({ src: items[0]?.url || '' })} /></div><div className="block-option-stack">{textInput('title', 'Título')}<label>Imagen<select value={block.side} onChange={(event) => onChange({ side: event.target.value })}><option value="left">Izquierda + texto derecha</option><option value="right">Texto izquierda + imagen derecha</option></select></label><RichTextEditor value={block.content} onChange={(content) => onChange({ content })} label="Texto" minHeight={150} /></div></div>;
  if (block.type === 'banner') return <div className="block-editor-grid"><MediaUploader value={[{ file: { name: block.src?.split('/').pop() || 'banner', type: 'image/*', size: 0 }, url: block.src }]} multiple={false} onChange={(items) => onChange({ src: items[0]?.url || '' })} /><div className="block-option-stack">{textInput('alt', 'Texto alternativo')}<label>Altura<select value={block.height} onChange={(event) => onChange({ height: event.target.value })}><option value="small">Baja</option><option value="medium">Media</option><option value="large">Alta</option><option value="screen">Pantalla completa</option></select></label><label>Opacidad de capa<input type="range" min="0" max=".8" step=".05" value={block.overlay} onChange={(event) => onChange({ overlay: Number(event.target.value) })} /></label></div></div>;
  if (block.type === 'video') return <div className="block-editor-grid"><div className="block-option-stack">{textInput('url', 'URL del video', 'url')}{textInput('title', 'Título')}<MediaUploader value={block.poster ? [{ file: { name: 'poster', type: 'image/*', size: 0 }, url: block.poster }] : []} multiple={false} label="Poster / miniatura" onChange={(items) => onChange({ poster: items[0]?.url || '' })} /></div><div className="block-editor-help">Admite enlaces de YouTube, Vimeo o un archivo de video gestionado por Supabase Storage.</div></div>;
  if (block.type === 'divider') return <div className="block-option-stack inline-options"><label>Estilo<select value={block.style} onChange={(event) => onChange({ style: event.target.value })}><option value="line">Línea</option><option value="dots">Puntos</option><option value="space">Solo espacio</option></select></label>{textInput('space', 'Espacio (px)', 'number')}</div>;
  if (block.type === 'button') return <div className="fields two">{textInput('label', 'Texto del botón')}{textInput('href', 'Enlace') }<label>Estilo<select value={block.variant} onChange={(event) => onChange({ variant: event.target.value })}><option value="primary">Naranja</option><option value="dark">Oscuro</option><option value="outline">Borde</option></select></label><label>Alineación<select value={block.align} onChange={(event) => onChange({ align: event.target.value })}><option value="left">Izquierda</option><option value="center">Centro</option><option value="right">Derecha</option></select></label></div>;
  if (block.type === 'social') return <div className="block-option-stack">{textInput('title', 'Título')}<RichTextEditor value={block.links.map((link) => `<p><a href="${link.href}">${link.label}</a></p>`).join('')} onChange={() => {}} label="Vista previa de redes" minHeight={110} /></div>;
  if (block.type === 'map') return <div className="fields two">{textInput('title', 'Título')}{textInput('address', 'Dirección')}{textInput('embedUrl', 'URL de embed del mapa')}</div>;
  if (block.type === 'embed') return <div className="block-option-stack">{textInput('label', 'Etiqueta')}<RichTextEditor value={block.html} onChange={(html) => onChange({ html })} label="HTML / embed" minHeight={170} /></div>;
  if (block.type === 'form') return <FormBlockEditor block={block} onChange={onChange} />;
  if (block.type === 'columns') return <ColumnsEditor block={block} onChange={onChange} />;
  return <div className="block-editor-help">Este bloque estará listo para configurar en la próxima iteración.</div>;
}

function ColumnsEditor({ block, onChange }) { const updateColumn = (index, blocks) => onChange({ columns: block.columns.map((column, columnIndex) => columnIndex === index ? { ...column, blocks } : column) }); return <div className="columns-editor">{block.columns.map((column, index) => <div key={column.id}><div className="columns-editor-head"><b>Columna {index + 1}</b><button type="button" onClick={() => updateColumn(index, [...column.blocks, createBlock('text')])}><Plus size={13} /> Bloque</button></div><BlockBuilder value={column.blocks} onChange={(blocks) => updateColumn(index, blocks)} title="Bloques de columna" fullscreen={false} /></div>)}</div>; }

function FormBlockEditor({ block, onChange }) { const fields = block.fields || []; const update = (index, patch) => onChange({ fields: fields.map((field, fieldIndex) => fieldIndex === index ? { ...field, ...patch } : field) }); return <div className="form-block-editor"><div className="fields two"><label>Título<input value={block.title} onChange={(event) => onChange({ title: event.target.value })} /></label><button type="button" className="button button-outline" onClick={() => onChange({ fields: [...fields, { key: `question-${Date.now()}`, label: 'Nueva pregunta', type: 'text', required: false }] })}><Plus size={15} /> Añadir pregunta</button></div>{fields.map((field, index) => <div className="question-editor-row" key={field.key}><span>{index + 1}</span><input value={field.label} onChange={(event) => update(index, { label: event.target.value })} /><select value={field.type} onChange={(event) => update(index, { type: event.target.value })}><option value="text">Texto</option><option value="textarea">Texto largo</option><option value="number">Número</option><option value="radio">Opción única</option><option value="checkbox">Múltiple</option><option value="select">Selector</option><option value="color">Color</option><option value="color-multi">Múltiples colores</option><option value="date">Fecha</option><option value="file">Archivo</option><option value="rating">Valoración</option></select><label><input type="checkbox" checked={field.required} onChange={(event) => update(index, { required: event.target.checked })} /> Obligatoria</label><button type="button" onClick={() => onChange({ fields: fields.filter((_, fieldIndex) => fieldIndex !== index) })}><Trash2 size={14} /></button></div>)}</div>; }

function BlockPreview({ blocks }) { return <div className="block-preview-content">{blocks.map((block) => <div className="preview-block" key={block.id}><span>{blockCatalog.find((item) => item.type === block.type)?.label || block.type}</span>{block.type === 'text' && <div dangerouslySetInnerHTML={{ __html: block.content }} />}{block.type === 'image' && <img src={assetPath(block.src)} alt="" />}{block.type === 'banner' && <img src={assetPath(block.src)} alt="" />}{block.type === 'gallery' && <MediaGallery items={block.items} layout={block.layout} columns={block.columns} />}</div>)}</div>; }
