import React, { useMemo, useState } from 'react';
import { ChevronLeft, ChevronRight, Clock3, Plus } from 'lucide-react';

const monthNames = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'];
const weekDays = ['Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb', 'Dom'];
const toKey = (date) => date.toISOString().slice(0, 10);

export function ModernCalendar({ events = [], value, onChange, selectable = true, compact = false }) {
  const today = new Date(); const initial = value ? new Date(value) : today; const [cursor, setCursor] = useState(new Date(initial.getFullYear(), initial.getMonth(), 1)); const [selected, setSelected] = useState(value || toKey(today));
  const days = useMemo(() => { const first = new Date(cursor.getFullYear(), cursor.getMonth(), 1); const offset = (first.getDay() + 6) % 7; const total = new Date(cursor.getFullYear(), cursor.getMonth() + 1, 0).getDate(); return Array.from({ length: Math.ceil((offset + total) / 7) * 7 }, (_, index) => { const day = index - offset + 1; return day < 1 || day > total ? null : new Date(cursor.getFullYear(), cursor.getMonth(), day); }); }, [cursor]);
  const pick = (date) => { if (!date || !selectable) return; const key = toKey(date); setSelected(key); onChange?.(key); };
  return <div className={`studio-calendar ${compact ? 'compact' : ''}`}><div className="studio-calendar-head"><button type="button" onClick={() => setCursor(new Date(cursor.getFullYear(), cursor.getMonth() - 1, 1))}><ChevronLeft size={16} /></button><div><b>{monthNames[cursor.getMonth()]}</b><span>{cursor.getFullYear()}</span></div><button type="button" onClick={() => setCursor(new Date(cursor.getFullYear(), cursor.getMonth() + 1, 1))}><ChevronRight size={16} /></button></div><div className="studio-calendar-week">{weekDays.map((day) => <span key={day}>{day}</span>)}</div><div className="studio-calendar-grid">{days.map((date, index) => { const key = date && toKey(date); const dayEvents = events.filter((event) => event.date === key); return <button type="button" key={key || `empty-${index}`} disabled={!date} className={`${key === selected ? 'selected ' : ''}${key === toKey(today) ? 'today ' : ''}${dayEvents.length ? 'has-events' : ''}`} onClick={() => pick(date)}>{date?.getDate()}{dayEvents.length > 0 && <i />}</button>; })}</div>{selected && <div className="studio-calendar-agenda"><div><span className="agenda-date">{new Date(`${selected}T12:00:00`).toLocaleDateString('es-EC', { day: 'numeric', month: 'long' })}</span><b>{events.filter((event) => event.date === selected).length ? 'Agenda del día' : 'Día disponible'}</b></div>{events.filter((event) => event.date === selected).map((event) => <div className="agenda-event" key={event.id || event.title}><span style={{ '--event-color': event.color || '#FF5B1F' }} /><div><b>{event.title}</b><small><Clock3 size={12} /> {event.time || 'Por confirmar'}</small></div></div>)}{!events.some((event) => event.date === selected) && <button type="button" className="agenda-add"><Plus size={13} /> Añadir evento</button>}</div>}</div>;
}
