import React, { useEffect, useMemo, useState } from 'react';
import { ArrowUp, Bell, Calculator, Check, Command, Home, Moon, Palette, Search, ShoppingBag, Sun, X } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';

export function ThemeToggle({ theme, onChange }) { const dark = theme === 'dark'; return <button type="button" className="theme-toggle" onClick={() => onChange?.(dark ? 'light' : 'dark')} aria-label="Cambiar modo de color">{dark ? <Sun size={15} /> : <Moon size={15} />}<span>{dark ? 'Claro' : 'Oscuro'}</span></button>; }

export function ToastViewport({ items = [], onDismiss }) { return <div className="studio-toasts" aria-live="polite">{items.map((item) => <div className={`studio-toast ${item.type || 'success'}`} key={item.id}><Check size={15} /><span>{item.message}</span><button type="button" onClick={() => onDismiss?.(item.id)}><X size={13} /></button></div>)}</div>; }

export function Dialog({ open, title, eyebrow = 'Ventana', children, onClose, footer }) { if (!open) return null; return <div className="studio-dialog-backdrop" role="dialog" aria-modal="true" onMouseDown={(event) => event.target === event.currentTarget && onClose?.()}><div className="studio-dialog"><header><div><span className="eyebrow orange">{eyebrow}</span><h2>{title}</h2></div><button type="button" onClick={onClose}><X size={18} /></button></header><div className="studio-dialog-body">{children}</div>{footer && <footer>{footer}</footer>}</div></div>; }

const searchItems = [{ label: 'Inicio', hint: 'Resumen público', href: '/' }, { label: 'Tienda', hint: 'Catálogo de productos', href: '/tienda' }, { label: 'Cotizador', hint: 'Calcula una idea', href: '/cotizador' }, { label: 'Contacto', hint: 'Habla con Gigaprint', href: '/contacto' }, { label: 'Admin / Editor', hint: 'Editar páginas y bloques', href: '/admin/editor' }];

export function SearchCommand({ extraItems = [] }) { const navigate = useNavigate(); const [open, setOpen] = useState(false); const [query, setQuery] = useState(''); const items = useMemo(() => [...searchItems, ...extraItems].filter((item) => `${item.label} ${item.hint}`.toLowerCase().includes(query.toLowerCase())), [extraItems, query]); useEffect(() => { const keydown = (event) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setOpen(true); } if (event.key === 'Escape') setOpen(false); }; window.addEventListener('keydown', keydown); return () => window.removeEventListener('keydown', keydown); }, []); return <>{open && <div className="search-command-backdrop" onMouseDown={(event) => event.target === event.currentTarget && setOpen(false)}><div className="search-command"><div className="search-command-input"><Search size={17} /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Busca una página, bloque o herramienta" /><kbd>ESC</kbd></div><div className="search-command-results">{items.map((item) => <button type="button" key={item.href || item.label} onClick={() => { setOpen(false); navigate(item.href); }}><span><b>{item.label}</b><small>{item.hint}</small></span><span>↗</span></button>)}{!items.length && <p>Sin resultados para “{query}”.</p>}</div><div className="search-command-foot"><Command size={13} /> Ctrl K para abrir · Esc para cerrar</div></div></div>}<button type="button" className="command-trigger" onClick={() => setOpen(true)}><Search size={15} /><span>Buscar</span><kbd>Ctrl K</kbd></button></>; }

export function ContextMenu({ items = [] }) { const [menu, setMenu] = useState(null); useEffect(() => { const close = () => setMenu(null); window.addEventListener('click', close); window.addEventListener('scroll', close, { passive: true }); let timer = null; let start = null; const isInteractive = (target) => target?.closest?.('input,textarea,select,button,a,[contenteditable="true"]'); const cancel = () => { if (timer) window.clearTimeout(timer); timer = null; start = null; }; const open = (x, y) => setMenu({ x: Math.min(x, window.innerWidth - 245), y: Math.min(y, window.innerHeight - Math.min(300, 46 * items.length + 18)) }); const context = (event) => { if (!items.length || isInteractive(event.target)) return; event.preventDefault(); open(event.clientX, event.clientY); }; const pointerDown = (event) => { if (!items.length || event.pointerType !== 'touch' || isInteractive(event.target)) return; start = { x: event.clientX, y: event.clientY }; timer = window.setTimeout(() => { if (start) { open(start.x, start.y); start = null; } }, 560); }; const pointerMove = (event) => { if (!start || Math.hypot(event.clientX - start.x, event.clientY - start.y) > 10) cancel(); }; window.addEventListener('contextmenu', context); window.addEventListener('pointerdown', pointerDown, { passive: true }); window.addEventListener('pointerup', cancel, { passive: true }); window.addEventListener('pointercancel', cancel, { passive: true }); window.addEventListener('pointermove', pointerMove, { passive: true }); return () => { cancel(); window.removeEventListener('click', close); window.removeEventListener('scroll', close); window.removeEventListener('contextmenu', context); window.removeEventListener('pointerdown', pointerDown); window.removeEventListener('pointerup', cancel); window.removeEventListener('pointercancel', cancel); window.removeEventListener('pointermove', pointerMove); }; }, [items]); if (!menu) return null; return <div className="studio-context-menu" style={{ left: menu.x, top: menu.y }} role="menu" onClick={(event) => event.stopPropagation()}>{items.map((item) => <button type="button" role="menuitem" key={item.label} disabled={item.disabled} onClick={() => { item.onClick?.(); setMenu(null); }}>{item.icon}<span>{item.label}</span>{item.shortcut && <kbd>{item.shortcut}</kbd>}</button>)}</div>; }

export function MotionObserver() { useEffect(() => { const reduce = window.matchMedia('(prefers-reduced-motion: reduce)').matches; const nodes = document.querySelectorAll('main > section, .service-card, .product-card, .promo-card, .quote-step, .quote-summary-card, .cta-card, .admin-card, .studio-tool-card'); if (reduce) { nodes.forEach((node) => node.classList.add('motion-visible')); return undefined; } nodes.forEach((node, index) => { node.classList.add('motion-reveal'); node.style.setProperty('--motion-delay', `${Math.min(index % 8, 7) * 55}ms`); }); const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('motion-visible'); observer.unobserve(entry.target); } }), { threshold: 0.08, rootMargin: '0px 0px -30px' }); nodes.forEach((node) => observer.observe(node)); return () => observer.disconnect(); }, []); return null; }

export function SeasonalThemeLayer({ preset }) { if (!preset || preset.id === 'default') return null; return <div className={`seasonal-layer seasonal-${preset.id}`} aria-hidden="true"><div className="seasonal-ribbon"><Palette size={13} /><span>{preset.label}</span></div><div className="seasonal-symbols">{preset.decorations.map((symbol, index) => <span key={`${symbol}-${index}`} style={{ '--seasonal-delay': `${index * 1.2}s` }}>{symbol}</span>)}</div></div>; }

export const contextIcons = { home: <Home size={15} />, store: <ShoppingBag size={15} />, quote: <Calculator size={15} />, palette: <Palette size={15} />, top: <ArrowUp size={15} /> };

export function ScrollToTop() { useEffect(() => { document.documentElement.style.scrollBehavior = 'smooth'; return () => { document.documentElement.style.scrollBehavior = ''; }; }, []); return null; }
