import React from 'react';
import { Check, Star } from 'lucide-react';
import { ColorPicker } from './ColorPicker';
import { MediaUploader } from './MediaUploader';

export function FieldRenderer({ field, value, onChange }) {
  const set = (next) => onChange?.(next);
  const common = { id: field.key, name: field.key, required: field.required, placeholder: field.placeholder || '', value: value ?? '', onChange: (event) => set(event.target.value) };
  return <div className={`studio-field studio-field-${field.type}`}><label htmlFor={field.key}><span>{field.label} {field.required && <em>*</em>}</span>{field.help && <small>{field.help}</small>}</label>{field.type === 'textarea' && <textarea {...common} rows={field.rows || 4} />}{['text', 'email', 'number', 'date', 'url'].includes(field.type) && <input {...common} type={field.type} />}{field.type === 'select' && <select {...common}>{!field.required && <option value="">Selecciona una opción</option>}{(field.options || []).map((option) => <option key={option} value={option}>{option}</option>)}</select>}{['radio', 'checkbox'].includes(field.type) && <div className="studio-options">{(field.options || []).map((option) => { const checked = field.type === 'checkbox' ? (value || []).includes(option) : value === option; return <label className={checked ? 'checked' : ''} key={option}><input type={field.type} name={field.key} value={option} checked={checked} onChange={() => set(field.type === 'checkbox' ? checked ? (value || []).filter((item) => item !== option) : [...(value || []), option] : option)} /><span><Check size={13} />{option}</span></label>; })}</div>}{field.type === 'color' && <ColorPicker value={value || '#FF5B1F'} onChange={set} />}{field.type === 'color-multi' && <ColorPicker value={value || ['#FF5B1F', '#171714']} multiple onChange={set} />}{field.type === 'file' && <MediaUploader value={value || []} onChange={set} multiple helper={field.help || undefined} />}{field.type === 'rating' && <div className="studio-rating">{Array.from({ length: field.max || 5 }, (_, index) => <button type="button" key={index} onClick={() => set(index + 1)} className={index < Number(value || 0) ? 'active' : ''}><Star size={21} fill="currentColor" /></button>)}</div>}</div>;
}

export function FormRenderer({ fields = [], values = {}, onChange, onSubmit, submitLabel = 'Enviar formulario' }) { return <form className="studio-form-renderer" onSubmit={(event) => { event.preventDefault(); onSubmit?.(values); }}>{fields.map((field) => <FieldRenderer key={field.key} field={field} value={values[field.key]} onChange={(next) => onChange?.({ ...values, [field.key]: next })} />)}<button className="button button-primary" type="submit">{submitLabel}</button></form>; }
